### ISSUE TITLE
Will the new version support Onenote vs Onenote 2016

### ISSUE THREAD

**Issue by that0n3guy** [AlexanderDemko/BibleNote#2]
I've used your plugin for years and loved it.  I know that the old onenote 2016 is no longer getting updates.

Will this new version work with the new onenote?

**Comment by AlexanderDemko** [comment]
There are two modern versions of OneNote: Universal Windows apps ("metro style" as it was called earlier) and classic desktop. Recently, only the traditional Office OneNote desktop version in Windows system has the ability to support add-ins. Other OneNote versions, like OneNote UWP, Android OneNote, IOS OneNote, and Mac OneNote do not have the ability to support add-ins. 
BibleNote works only with classic desktop version of OneNote. The latest one such a version is 2016.
