### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by daniel-odrinski** [AlexanderDemko/BibleNote#24]
Hi,
How can I contribute to this project source code-wise?
I see that the README contains what appears to be a roadmap/checklist.

Thanks.

**Comment by AlexanderDemko** [comment]
Sure, you can.
What is your technology stack?

**Comment by daniel-odrinski** [comment]
Mainly Java, JavaFX, Golang, HTML5, CSS3, some JS, but I've been looking to learn more about C# lately. This may be a good opportunity.

**Comment by daniel-odrinski** [comment]
Oh, I see that the client app is mainly developed using Angular. So, I'm not sure how useful my contributions would be given that I have no experience so far... Thanks for your time and efforts!
