### ISSUE TITLE
Have you seen obsidian.md?

### ISSUE THREAD

**Issue by that0n3guy** [AlexanderDemko/BibleNote#5]
I've been a onenote user for 6 years (I feel like my life is in that thing), but I just came across https://obsidian.md/ .  I'm going to spend the month using it instead of onenote as I see some potential.

I think it would be PERFECT for a biblenote plugin b/c of its linking/backlinking capabilities.  It has plugins so it should be WAY easier to do than onenote's new system... and the customer base is growing fast.  There are a lot of developers on there and their discord channel is great.

There are also [those out there using it for the bible](https://forum.obsidian.md/t/organising-the-bible-in-obsidian/1490).  The community would benefit from this plugin for auto linking on standard bible reference variations (jn 3:16, john 3:16, etc..)

I'd love to know your thoughts!

**Comment by AlexanderDemko** [comment]
This is a good idea. But it looks like a brand new project. I have no free time for it. May be in future.
There are a lot of work with new BibleNote 4 that I wish to implement.
