### ISSUE TITLE
Offer To help 

### ISSUE THREAD

**Issue by claywd** [AlexanderDemko/BibleNote#6]
I want to get involved. Immediate thing I can help with is the website. Https , CMS, payment solutions, devOps , etc. 

I dev as well but not C# yet.

Do you have discord or slack setup? If not I can help there too.

Interested in help?

**Comment by AlexanderDemko** [comment]
Sure. Would be glad.
1. What is your native language? Do you speak Russian?
2. What do you mean by "https"? Do you know js, css, html? What about Angular and Electron?

**Comment by claywd** [comment]
1. English no russian currently
2. I mean I can set you up with TLS support on your website. I actually program in Golang, C++, python and a little js. I dabble in  the frontend stuff but nothing too heavy. 

Seems like the site is offline for the moment. I hope yall are safe

**Comment by AlexanderDemko** [comment]
Thanks for your offer of help.
But there is no need to configure TLS at this moment.
